#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define COUNT_MAX_L 300
#define COUNT_MID_R 500
#define COUNT_MAX_R 1000


#define MAX_L_POWER
#define MIN_L_POWER
#define MAX_R_POWER
#define MIN_R_POWER

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	int counter = 0;
	bool onLine = SensorValue(lightSensor) < 45;

	bPlaySounds = true;

	while(true)                           // Infinite loop
	{
		nxtDisplayTextLine(3, "Light: %d", SensorValue(lightSensor));
	}
}
