#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	nMotorPIDSpeedCtrl[leftWheel] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[rightWheel] = mtrSpeedReg;
	
	int turning_wheel;
	int straight_wheel;
	int soft_turn;
	int hard_turn;
	int counter = 0;
	bool onLine = SensorValue(lightSensor) < 55;

	bPlaySounds = true;

	while(true)                           // Infinite loop
	{
		nxtDisplayTextLine(3, "Counter: %d", counter);
		nxtDisplayTextLine(4, "onLine: %d", onLine);

		if (SensorValue(lightSensor) < 55)
		{
			//we are INSIDE the line, need to turn left
			turning_wheel = leftWheel;
			straight_wheel = rightWheel;
			if(!onLine) {
				counter = 0;
				onLine = true;
			}
			soft_turn = 100;
			hard_turn = 200;
		}

		else {
			//do not see the line, need to turn right
			turning_wheel = rightWheel;
			straight_wheel = leftWheel;
			if(onLine) {
				counter = 0;
				onLine = false;
			}
			soft_turn = 800;
			hard_turn = 1000;
		}
		
		

		if (counter > hard_turn) {
				if (!bSoundActive) {
					playSound(soundBlip);
				}

				// going same way too long, sharp turn
				motor[straight_wheel] = 40;
				motor[turning_wheel] = -40;
		}
		
		else if (counter > soft_turn) {
				// slight turn
				motor[straight_wheel] = 30;
				motor[turning_wheel] = 0;
		}
		
		else {
			motor[straight_wheel] = 40;
			motor[turning_wheel] = 10;
		}
		
		counter++;
	}
}
