#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define COUNT_MAX_L 300
#define COUNT_MID_R 250
#define COUNT_MAX_R 1000


#define MAX_L_POWER
#define MIN_L_POWER
#define MAX_R_POWER
#define MIN_R_POWER

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	int counter = 0;
	bool onLine = SensorValue(lightSensor) < 55;

	bPlaySounds = true;

	while(true)                           // Infinite loop
	{
		nxtDisplayTextLine(3, "Counter: %d", counter);
		nxtDisplayTextLine(4, "onLine: %d", onLine);


		if (SensorValue(lightSensor) < 55)
		{
			// We are INSIDE the line
			if (!onLine)
			{
				// if we were outside the line before, reset the counter
				counter = 0;
				onLine = true;
			}

			if (counter > COUNT_MAX_L)
			{
				if (!bSoundActive)
				{
					//playSound(soundBlip);
				}
				// If we have been going left for too long
				motor[rightWheel] = 15;
				motor[leftWheel] = -15;
			}
			else
			{
				// slight left
				motor[rightWheel] = 15;
				motor[leftWheel] = 0;
				counter++;
			}

		}
		else
		{
			// We are OUTSIDE the line
			if (onLine)
			{
				// if we were inside the line before, reset the counter
				counter = 0;
				onLine = false;
			}

			if (counter > COUNT_MAX_R)
			{
				if (!bSoundActive)
				{
					playSound(soundBlip);
				}
				// if we have been going right for too long
				motor[rightWheel] = -15;
				motor[leftWheel] = 15;
			}
			else if (counter > COUNT_MID_R)
			{
				motor[rightWheel] = 20 - (counter - COUNT_MID_R) / 25;
				motor[leftWheel] = 30;
				counter++;
			}
			else
			{
				// slight right
				motor[rightWheel] = 20;
				motor[leftWheel] = 30;
				counter++;
			}
		}
	}
}
