#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          rightWheel,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftWheel,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define COUNT_MAX_L 150
#define COUNT_MAX_R 800

#define MID_LIGHT 55

task main()
{
	wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.

	int counter = 0;
	bool onLine = SensorValue(lightSensor) < MID_LIGHT;

	int val;
	int powDiff;
	bPlaySounds = true;

	while(true)                           // Infinite loop
	{
		nxtDisplayTextLine(3, "Counter: %d", counter);
		nxtDisplayTextLine(4, "onLine: %d", onLine);

		val = SensorValue(lightSensor);

		if (val < MID_LIGHT)
		{
			// We are INSIDE the line
			if (!onLine)
			{
				// if we were outside the line before, reset the counter
				counter = 0;
				onLine = true;
			}
			if (counter > COUNT_MAX_L)
			{
				motor[rightWheel] = 15;
				motor[leftWheel] = -15;
				continue;
			}
			else
			{
				powDiff = (val - MID_LIGHT) * 5;
				motor[rightWheel] = 20 - powDiff;
				motor[leftWheel] = 20 + powDiff;
				counter++;
			}
		}
		else
		{
			if (onLine)
			{
				// if we were outside the line before, reset the counter
				counter = 0;
				onLine = false;
			}
			if (counter > COUNT_MAX_R)
			{
				if (!bSoundActive)
				{
					playSound(soundBlip);
				}
				motor[rightWheel] = -15;
				motor[leftWheel] = 15;
				continue;
			}
			else
			{
				powDiff = (val - MID_LIGHT) * 5;
				motor[rightWheel] = 20 - powDiff;
				motor[leftWheel] = 20 + powDiff;
				counter++;
			}
		}

	}
}
